import { InterchainNetwork } from "../types/network";

export const MAINNET: Record<string, InterchainNetwork> = {
  "akashnet-2": {
    baseAsset: "uakt",
    chainID: "akashnet-2",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/akash/account/{}",
      block: "https://www.mintscan.io/akash/blocks/id/{}",
      tx: "https://www.mintscan.io/akash/txs/{}",
      validator: "https://www.mintscan.io/akash/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      uakt: 0.025,
    },
    ibc: {
      fromTerra: "channel-45",
      toTerra: "channel-56",
    },
    icon: "https://station-assets.terra.money/img/chains/Akash.svg",
    lcd: "https://rest.cosmos.directory/akash",
    name: "Akash",
    prefix: "akash",
    tokens: null,
  },
  "axelar-dojo-1": {
    baseAsset: "uaxl",
    chainID: "axelar-dojo-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/axelar/account/{}",
      block: "https://www.mintscan.io/axelar/blocks/id/{}",
      tx: "https://www.mintscan.io/axelar/txs/{}",
      validator: "https://www.mintscan.io/axelar/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      uaxl: 0.007,
    },
    ibc: {
      fromTerra: "channel-6",
      toTerra: "channel-11",
    },
    icon: "https://station-assets.terra.money/img/chains/Axelar.svg",
    lcd: "https://lcd-axelar.imperator.co",
    name: "Axelar",
    prefix: "axelar",
    tokens: null,
  },
  "carbon-1": {
    baseAsset: "swth",
    chainID: "carbon-1",
    coinType: "118",
    explorer: {
      address: "https://scan.carbon.network/account/{}?net=main",
      block: "https://scan.carbon.network/block/{}?net=main",
      tx: "https://scan.carbon.network/transaction/{}?net=main",
      validator: "https://scan.carbon.network/validator/{}?net=main",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      swth: 1000,
    },
    ibc: {
      fromTerra: "channel-36",
      toTerra: "channel-12",
    },
    icon: "https://switcheo-assets.s3.ap-southeast-1.amazonaws.com/Carbon.svg",
    lcd: "https://query-api.carbon.network/",
    name: "Carbon",
    prefix: "swth",
    tokens: null,
  },
  "chihuahua-1": {
    baseAsset: "uhuahua",
    chainID: "chihuahua-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/chihuahua/account/{}",
      block: "https://www.mintscan.io/chihuahua/blocks/id/{}",
      tx: "https://www.mintscan.io/chihuahua/txs/{}",
      validator: "https://www.mintscan.io/chihuahua/validators/{}",
    },
    gasAdjustment: 2,
    gasPrices: {
      uhuahua: 1,
    },
    ibc: {
      fromTerra: "channel-44",
      toTerra: "channel-34",
    },
    icon: "https://station-assets.terra.money/img/chains/Huahua.png",
    lcd: "https://api.chihuahua.wtf",
    name: "Chihuahua",
    prefix: "chihuahua",
    tokens: null,
  },
  "comdex-1": {
    baseAsset: "ucmdx",
    chainID: "comdex-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/comdex/account/{}",
      block: "https://www.mintscan.io/comdex/blocks/id/{}",
      tx: "https://www.mintscan.io/comdex/txs/{}",
      validator: "https://www.mintscan.io/comdex/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      ucmdx: 0.0025,
    },
    ibc: {
      fromTerra: "channel-39",
      toTerra: "channel-51",
    },
    icon: "https://station-assets.terra.money/img/chains/Comdex.svg",
    lcd: "https://rest.comdex.one",
    name: "Comdex",
    prefix: "comdex",
    tokens: null,
  },
  "crescent-1": {
    baseAsset: "ucre",
    chainID: "crescent-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/crescent/account/{}",
      block: "https://www.mintscan.io/crescent/blocks/id/{}",
      tx: "https://www.mintscan.io/crescent/txs/{}",
      validator: "https://www.mintscan.io/crescent/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      ucre: 0.01,
    },
    ibc: {
      fromTerra: "channel-37",
      toTerra: "channel-27",
    },
    icon: "https://station-assets.terra.money/img/chains/Crescent.svg",
    lcd: "https://mainnet.crescent.network:1317",
    name: "Crescent",
    prefix: "cre",
    tokens: null,
  },
  "kaiyo-1": {
    baseAsset: "ukuji",
    chainID: "kaiyo-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/kujira/account/{}",
      block: "https://www.mintscan.io/kujira/blocks/id/{}",
      tx: "https://www.mintscan.io/kujira/txs/{}",
      validator: "https://www.mintscan.io/kujira/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      "ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F": 0.0015,
      "ibc/DA59C009A0B3B95E0549E6BF7B075C8239285989FF457A8EDDBB56F10B2A6986": 0.000625,
      ukuji: 0.00119,
    },
    ibc: {
      fromTerra: "channel-10",
      icsFromTerra: {
        contract:
          "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
        fromTerra: "channel-28",
        toTerra: "channel-36",
      },
      toTerra: "channel-5",
    },
    icon: "https://station-assets.terra.money/img/chains/Kujira.png",
    lcd: "https://lcd.kaiyo.kujira.setten.io",
    name: "Kujira",
    prefix: "kujira",
    tokens: null,
  },
  "mars-1": {
    baseAsset: "umars",
    chainID: "mars-1",
    coinType: "330",
    explorer: {
      address: "https://explorer.marsprotocol.io/accounts/{}",
      block: "https://explorer.marsprotocol.io/blocks/{}",
      tx: "https://explorer.marsprotocol.io/transactions/{}",
      validator: "https://explorer.marsprotocol.io/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      umars: 0,
    },
    ibc: {
      fromTerra: "channel-78",
      toTerra: "channel-2",
    },
    icon: "https://station-assets.terra.money/img/chains/Mars.svg",
    lcd: "https://rest.marsprotocol.io",
    name: "Mars",
    prefix: "mars",
    tokens: null,
    version: "0.46",
  },
  "migaloo-1": {
    baseAsset: "uwhale",
    chainID: "migaloo-1",
    coinType: "118",
    explorer: {
      address: "https://ping.pub/migaloo/account/{}",
      block: "https://ping.pub/migaloo/blocks/id/{}",
      tx: "https://ping.pub/migaloo/txs/{}",
      validator: "https://ping.pub/migaloo/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      uwhale: 0.25,
    },
    ibc: {
      fromTerra: "channel-86",
      icsFromTerra: {
        contract:
          "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
        fromTerra: "channel-87",
        toTerra: "channel-2",
      },
      toTerra: "channel-0",
    },
    icon: "https://station-assets.terra.money/img/chains/Migaloo.svg",
    lcd: "https://ww-migaloo-rest.polkachu.com",
    name: "Migaloo",
    prefix: "migaloo",
    tokens: null,
  },
  "osmosis-1": {
    baseAsset: "uosmo",
    chainID: "osmosis-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/osmosis/account/{}",
      block: "https://www.mintscan.io/osmosis/blocks/id/{}",
      tx: "https://www.mintscan.io/osmosis/txs/{}",
      validator: "https://www.mintscan.io/osmosis/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      uosmo: 0.025,
    },
    ibc: {
      fromTerra: "channel-1",
      icsFromTerra: {
        contract:
          "terra1e0mrzy8077druuu42vs0hu7ugguade0cj65dgtauyaw4gsl4kv0qtdf2au",
        fromTerra: "channel-26",
        toTerra: "channel-341",
      },
      toTerra: "channel-251",
    },
    icon: "https://station-assets.terra.money/img/chains/Osmosis.svg",
    lcd: "https://osmosis-1.terra.dev",
    name: "Osmosis",
    prefix: "osmo",
    tokens: null,
  },
  "phoenix-1": {
    baseAsset: "uluna",
    chainID: "phoenix-1",
    coinType: "330",
    explorer: {
      address: "https://terrasco.pe/mainnet/address/{}",
      block: "https://terrasco.pe/mainnet/block/{}",
      tx: "https://terrasco.pe/mainnet/tx/{}",
      validator: "https://terrasco.pe/mainnet/validator/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      uluna: 0.015,
    },
    icon: "https://station-assets.terra.money/img/chains/Terra.svg",
    lcd: "https://phoenix-lcd.terra.dev",
    name: "Terra",
    prefix: "terra",
    tokens: null,
  },
  "stride-1": {
    baseAsset: "ustrd",
    chainID: "stride-1",
    coinType: "118",
    explorer: {
      address: "https://www.mintscan.io/stride/account/{}",
      block: "https://www.mintscan.io/stride/blocks/id/{}",
      tx: "https://www.mintscan.io/stride/txs/{}",
      validator: "https://www.mintscan.io/stride/validators/{}",
    },
    gasAdjustment: 1.75,
    gasPrices: {
      ustrd: 0,
    },
    ibc: {
      fromTerra: "channel-46",
      toTerra: "channel-52",
    },
    icon: "https://station-assets.terra.money/img/chains/Stride.png",
    lcd: "https://stride-fleet.main.stridenet.co/api",
    name: "Stride",
    prefix: "stride",
    tokens: null,
  },
};

export const TESTNET: Record<string, InterchainNetwork> = {
  "uni-5": {
    chainID: "uni-5",
    lcd: "https://juno-testnet-api.polkachu.com",
    gasAdjustment: 2,
    gasPrices: {
      ujunox: 0.015,
    },
    prefix: "juno",
    coinType: "118",
    baseAsset: "ujunox",
    name: "Juno",
    icon: "https://station-assets.terra.money/img/chains/Juno.svg",
    explorer: {},
    tokens: null,
  },
  "ares-1": {
    chainID: "ares-1",
    lcd: "https://testnet-rest.marsprotocol.io",
    gasAdjustment: 2,
    gasPrices: {
      umars: 0,
    },
    prefix: "mars",
    coinType: "330",
    baseAsset: "umars",
    name: "Mars",
    icon: "https://station-assets.terra.money/img/chains/Mars.svg",
    ibc: {
      toTerra: "channel-0",
      fromTerra: "channel-189",
    },
    version: "0.46",
    explorer: {
      address: "https://testnet-explorer.marsprotocol.io/accounts/{}",
      tx: "https://testnet-explorer.marsprotocol.io/transactions/{}",
      validator: "https://testnet-explorer.marsprotocol.io/validators/{}",
      block: "https://testnet-explorer.marsprotocol.io/blocks/{}",
    },
    tokens: null,
  },
  "atlantic-1": {
    chainID: "atlantic-1",
    lcd: "https://sei-testnet-rpc.polkachu.com",
    gasAdjustment: 2,
    gasPrices: {
      usei: 0.01,
    },
    prefix: "sei",
    coinType: "118",
    baseAsset: "usei",
    name: "Sei",
    icon: "https://station-assets.terra.money/img/chains/Sei.png",
    ibc: {
      fromTerra: "channel-100",
      toTerra: "channel-11",
    },
    explorer: {},
    tokens: null,
  },
  "pisco-1": {
    chainID: "pisco-1",
    lcd: "https://pisco-lcd.terra.dev",
    gasAdjustment: 3.5,
    gasPrices: {
      uluna: 0.015,
    },
    prefix: "terra",
    coinType: "330",
    baseAsset: "uluna",
    name: "Terra",
    icon: "https://station-assets.terra.money/img/chains/Terra.svg",
    explorer: {
      address: "https://terrasco.pe/testnet/address/{}",
      tx: "https://terrasco.pe/testnet/tx/{}",
      validator: "https://terrasco.pe/testnet/validator/{}",
      block: "https://terrasco.pe/testnet/block/{}",
    },
    tokens: null,
  },
};
